server:
  http_listen_port: 9080
  grpc_listen_port: 0

# It is needed for when Promtail is restarted to allow it to continue from where it left off.
positions: 
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: compose  # A `job` label is fairly standard in prometheus and useful for linking metrics and logs.
      host: postgresql-node # A `host` label will help identify logs from this machine vs others
      __path__: /var/log/*.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar