version: "3.8"
name: postgresql-compose
services:
  postgres:
    container_name: postgresql-container
    image: postgres:16.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      PGDATA: /data/postgres
    volumes:
      - postgres-vol:/data/postgres
      - ./data/periodic_table.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/data/postgres/postgresql.conf
      - ./backup:/backup
    ports:
      - "5432:5432"
    networks:
      - pgvnet
    restart: unless-stopped
networks:
  pgvnet:
    driver: bridge
volumes:
  postgres-vol:
