version: "3"
services:
  postgres-exporter:
    container_name: postgres-exporter-container
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: postgresql://admin:supersecret@postgres:5432/postgres?sslmode=disable
    ports:
      - 9187:9187
    command:
      - --config.file=/etc/config/postgres_exporter.yaml
  alertmanager:
    container_name: alertmanager-container
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/rule_config.yml:/etc/alertmanager/config.yml
  grafana:
    container_name: grafana-container
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=scylladb-scylla-datasource
      # This is where you set Grafana security
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    image: grafana/grafana:10.3.5
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/var/lib/grafana/provisioning/datasources
      - grafana-vol:/var/lib/grafana
  loki:
    command:
      - --config.file=/mnt/config/loki-config.yaml
    container_name: loki-container
    image: grafana/loki:2.9.5
    privileged: true
    user: root
    ports:
      - 3100:3100
    volumes:
      # - ./loki/rules:/etc/loki/rules
      # - ./loki/conf:/mnt/config
      - loki-wal:/wal
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    container_name: prometheus-container
    image: prom/prometheus:v2.51.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-vol:/prometheus
  promtail:
    command:
      - --config.file=/etc/promtail/config.yaml
    container_name: promtail-container
    image: grafana/promtail:2.9.5
    ports:
      - 1514:1514
      - 9080:9080
    volumes:
      - ./loki/promtail/promtail.yaml:/etc/promtail/config.yaml
networks:
  default:
    external: true # join to the docker cluster network
    name: postgres-compose_pgvnet
volumes:
  grafana-vol:
  loki-wal:
  prometheus-vol: